export type QuestionType = 'single' | 'multiple' | 'scale' | 'text' | 'number'

export interface Question {
  id: string
  category: 'profile' | 'forge' | 'morphee' | 'fuel' | 'zenith' | 'atlas' | 'oracle'
  categoryLabel: string
  type: QuestionType
  question: string
  subtitle?: string
  options?: string[]
  min?: number
  max?: number
  unit?: string
  placeholder?: string
  required?: boolean
  memberField: string
}

export const QUESTIONS: Question[] = [
  // ─── PROFIL DE BASE (1-10) ────────────────────────────────────────────────
  {
    id: 'q01',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'text',
    question: 'Quel est votre prénom ?',
    subtitle: 'Pour personnaliser vos agents',
    placeholder: 'Prénom',
    required: true,
    memberField: 'full_name',
  },
  {
    id: 'q02',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'number',
    question: 'Quel est votre âge ?',
    min: 16,
    max: 99,
    unit: 'ans',
    required: true,
    memberField: 'age',
  },
  {
    id: 'q03',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'single',
    question: 'Quel est votre genre ?',
    options: ['Homme', 'Femme', 'Non-binaire', 'Préfère ne pas répondre'],
    required: true,
    memberField: 'gender',
  },
  {
    id: 'q04',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'number',
    question: 'Votre taille ?',
    min: 140,
    max: 220,
    unit: 'cm',
    required: true,
    memberField: 'height_cm',
  },
  {
    id: 'q05',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'number',
    question: 'Votre poids ?',
    min: 40,
    max: 200,
    unit: 'kg',
    required: true,
    memberField: 'weight_kg',
  },
  {
    id: 'q06',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'single',
    question: 'Votre objectif principal avec NATICS Lab ?',
    options: [
      'Améliorer mes performances sportives',
      'Optimiser mon sommeil et ma récupération',
      'Mieux gérer mon stress et ma santé mentale',
      'Optimiser ma nutrition et ma supplémentation',
      'Préparer une expédition ou un challenge physique',
      'Suivi global de ma santé de précision',
    ],
    required: true,
    memberField: 'primary_goal',
  },
  {
    id: 'q07',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'single',
    question: 'Votre niveau d\'activité physique actuel ?',
    options: [
      'Sédentaire (peu ou pas d\'exercice)',
      'Légèrement actif (1-2 fois/semaine)',
      'Modérément actif (3-4 fois/semaine)',
      'Très actif (5-6 fois/semaine)',
      'Extrêmement actif (2x/jour ou athlète)',
    ],
    required: true,
    memberField: 'activity_level',
  },
  {
    id: 'q08',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'text',
    question: 'Avez-vous des pathologies chroniques déclarées ?',
    subtitle: 'Diabète, hypertension, thyroïde… Vos agents en tiendront compte',
    placeholder: 'Aucune, ou décrivez ici',
    memberField: 'health_conditions',
  },
  {
    id: 'q09',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'text',
    question: 'Prenez-vous des médicaments régulièrement ?',
    subtitle: 'Pour vérifier les interactions avec vos prescriptions NATICS',
    placeholder: 'Aucun, ou listez-les',
    memberField: 'medications',
  },
  {
    id: 'q10',
    category: 'profile',
    categoryLabel: 'Votre profil',
    type: 'single',
    question: 'Où en êtes-vous avec le suivi de votre santé ?',
    options: [
      'Novice — je commence à m\'y intéresser',
      'Engagé — je suis déjà quelques données',
      'Expert — biohacking, biomarqueurs, wearables',
    ],
    memberField: 'health_tracking_level',
  },

  // ─── FORGE — ENTRAÎNEMENT (11-22) ────────────────────────────────────────
  {
    id: 'q11',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'multiple',
    question: 'Quels sports ou activités pratiquez-vous ?',
    subtitle: 'Sélectionnez tout ce qui s\'applique',
    options: [
      'Course à pied / Trail',
      'Cyclisme / Vélo',
      'Natation / Triathlon',
      'Musculation / Fitness',
      'CrossFit / HIIT',
      'Sports collectifs',
      'Arts martiaux',
      'Yoga / Pilates',
      'Escalade / Sports outdoor',
      'Aucun pour le moment',
    ],
    memberField: 'sports',
  },
  {
    id: 'q12',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'scale',
    question: 'Combien de sessions d\'entraînement par semaine ?',
    min: 0,
    max: 14,
    unit: 'sessions',
    memberField: 'training_frequency',
  },
  {
    id: 'q13',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Quelle est la durée moyenne d\'une session ?',
    options: [
      'Moins de 30 minutes',
      '30 à 60 minutes',
      '60 à 90 minutes',
      'Plus de 90 minutes',
    ],
    memberField: 'training_duration',
  },
  {
    id: 'q14',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Comment évaluez-vous votre niveau ?',
    options: [
      'Débutant — j\'apprends les bases',
      'Intermédiaire — je m\'entraîne régulièrement',
      'Avancé — je performe à haut niveau',
      'Élite — compétition ou niveau pro',
    ],
    memberField: 'performance_level',
  },
  {
    id: 'q15',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Votre objectif d\'entraînement prioritaire ?',
    options: [
      'Force et puissance',
      'Hypertrophie (prise de masse)',
      'Endurance et cardio',
      'Mobilité et flexibilité',
      'Perte de poids',
      'Polyvalence et santé générale',
    ],
    memberField: 'training_goal',
  },
  {
    id: 'q16',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'scale',
    question: 'Comment évaluez-vous votre récupération entre les sessions ?',
    subtitle: '1 = très mauvaise, 10 = excellente',
    min: 1,
    max: 10,
    memberField: 'recovery_rating',
  },
  {
    id: 'q17',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Quel équipement avez-vous à disposition ?',
    options: [
      'Salle de sport complète',
      'Équipements à domicile',
      'Entraînement en extérieur',
      'Peu ou pas d\'équipement',
    ],
    memberField: 'equipment_access',
  },
  {
    id: 'q18',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Avez-vous un coach ou programme d\'entraînement structuré ?',
    options: ['Oui, un coach personnel', 'Oui, un programme en ligne', 'Non, je m\'entraîne seul'],
    memberField: 'has_coach',
  },
  {
    id: 'q19',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'text',
    question: 'Avez-vous des blessures récentes ou chroniques ?',
    subtitle: 'FORGE adaptera les intensités en conséquence',
    placeholder: 'Aucune, ou décrivez',
    memberField: 'injuries',
  },
  {
    id: 'q20',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Comment percevez-vous votre vitesse de récupération ?',
    options: [
      'Lente — j\'ai besoin de plusieurs jours',
      'Normale — 24-48h suffisent',
      'Rapide — je récupère en moins de 24h',
    ],
    memberField: 'recovery_speed',
  },
  {
    id: 'q21',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'single',
    question: 'Avez-vous déjà testé votre VO2 max ou vos seuils lactiques ?',
    options: ['Oui, en laboratoire', 'Oui, via wearable', 'Non, jamais'],
    memberField: 'has_vo2_test',
  },
  {
    id: 'q22',
    category: 'forge',
    categoryLabel: 'FORGE — Entraînement',
    type: 'number',
    question: 'Votre fréquence cardiaque au repos estimée ?',
    subtitle: 'Au réveil, sans effort. Laissez vide si inconnue',
    min: 30,
    max: 100,
    unit: 'bpm',
    placeholder: 'Ex. 58',
    memberField: 'resting_hr',
  },

  // ─── MORPHÉE — SOMMEIL (23-32) ────────────────────────────────────────────
  {
    id: 'q23',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'scale',
    question: 'Combien d\'heures dormez-vous par nuit en moyenne ?',
    min: 4,
    max: 12,
    unit: 'heures',
    memberField: 'sleep_hours',
  },
  {
    id: 'q24',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'scale',
    question: 'Comment évaluez-vous la qualité de votre sommeil ?',
    subtitle: '1 = très mauvaise, 10 = excellente',
    min: 1,
    max: 10,
    memberField: 'sleep_quality',
  },
  {
    id: 'q25',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'single',
    question: 'À quelle heure vous couchez-vous habituellement ?',
    options: [
      'Avant 21h',
      '21h – 22h',
      '22h – 23h',
      '23h – minuit',
      'Après minuit',
    ],
    memberField: 'bedtime',
  },
  {
    id: 'q26',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'single',
    question: 'À quelle heure vous levez-vous habituellement ?',
    options: [
      'Avant 6h',
      '6h – 7h',
      '7h – 8h',
      '8h – 9h',
      'Après 9h',
    ],
    memberField: 'wake_time',
  },
  {
    id: 'q27',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'multiple',
    question: 'Avez-vous des troubles du sommeil ?',
    options: [
      'Difficultés à m\'endormir',
      'Réveils nocturnes fréquents',
      'Apnée du sommeil',
      'Cauchemars ou parasomnies',
      'Jambes sans repos',
      'Aucun trouble particulier',
    ],
    memberField: 'sleep_issues',
  },
  {
    id: 'q28',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'single',
    question: 'À quelle fréquence vous réveillez-vous la nuit ?',
    options: ['Jamais', 'Rarement (1-2x/semaine)', 'Parfois (3-4x/semaine)', 'Souvent (presque chaque nuit)'],
    memberField: 'night_awakenings',
  },
  {
    id: 'q29',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'scale',
    question: 'Vous sentez-vous reposé au réveil ?',
    subtitle: '1 = épuisé, 10 = parfaitement reposé',
    min: 1,
    max: 10,
    memberField: 'morning_freshness',
  },
  {
    id: 'q30',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'multiple',
    question: 'Utilisez-vous des aides au sommeil ?',
    options: [
      'Mélatonine',
      'Magnésium',
      'CBD',
      'Tisanes / plantes',
      'Médicaments prescrits',
      'Aucune',
    ],
    memberField: 'sleep_aids',
  },
  {
    id: 'q31',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'single',
    question: 'Avez-vous un rituel du soir avant de dormir ?',
    options: ['Oui, systématiquement', 'Oui, parfois', 'Non, pas vraiment'],
    memberField: 'has_evening_routine',
  },
  {
    id: 'q32',
    category: 'morphee',
    categoryLabel: 'MORPHÉE — Sommeil',
    type: 'single',
    question: 'Quelle est votre exposition aux écrans le soir ?',
    options: [
      'Je coupe les écrans 2h avant',
      '1 à 2 heures avant le coucher',
      'Jusqu\'au moment de dormir',
    ],
    memberField: 'screen_time_evening',
  },

  // ─── FUEL — NUTRITION (33-44) ─────────────────────────────────────────────
  {
    id: 'q33',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Quel est votre type alimentaire ?',
    options: [
      'Omnivore',
      'Végétarien',
      'Vegan',
      'Keto / Low-carb',
      'Carnivore',
      'Paleo',
      'Autre',
    ],
    memberField: 'diet_type',
  },
  {
    id: 'q34',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'scale',
    question: 'Combien de repas faites-vous par jour en moyenne ?',
    min: 1,
    max: 7,
    unit: 'repas',
    memberField: 'meal_frequency',
  },
  {
    id: 'q35',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'multiple',
    question: 'Avez-vous des allergies ou intolérances alimentaires ?',
    options: [
      'Gluten',
      'Lactose',
      'Fruits à coque',
      'Œufs',
      'Soja',
      'Fruits de mer',
      'Aucune',
    ],
    memberField: 'food_allergies',
  },
  {
    id: 'q36',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Suivez-vous vos apports caloriques ou macros ?',
    options: [
      'Oui, régulièrement',
      'Parfois, de façon approximative',
      'Non, jamais',
    ],
    memberField: 'tracks_calories',
  },
  {
    id: 'q37',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'scale',
    question: 'Quelle est votre hydratation quotidienne ?',
    subtitle: 'En litres d\'eau par jour',
    min: 0,
    max: 5,
    unit: 'litres',
    memberField: 'hydration_liters',
  },
  {
    id: 'q38',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'multiple',
    question: 'Quels compléments alimentaires prenez-vous actuellement ?',
    options: [
      'Protéines (whey, végétales)',
      'Créatine',
      'Oméga-3',
      'Vitamine D',
      'Magnésium',
      'Zinc',
      'Multivitamines',
      'Adaptogènes (ashwagandha, rhodiola…)',
      'Aucun',
    ],
    memberField: 'supplements',
  },
  {
    id: 'q39',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'scale',
    question: 'Votre niveau d\'énergie après les repas ?',
    subtitle: '1 = somnolent / lourd, 10 = énergie stable et durable',
    min: 1,
    max: 10,
    memberField: 'post_meal_energy',
  },
  {
    id: 'q40',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Sautez-vous des repas régulièrement ?',
    options: ['Jamais', 'Rarement', 'Parfois', 'Souvent (jeûne intermittent inclus)'],
    memberField: 'skips_meals',
  },
  {
    id: 'q41',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Consommez-vous de l\'alcool ?',
    options: [
      'Jamais',
      'Moins d\'une fois par semaine',
      '1 à 3 fois par semaine',
      'Plus de 3 fois par semaine',
    ],
    memberField: 'alcohol_consumption',
  },
  {
    id: 'q42',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Quelle est votre consommation de caféine ?',
    options: [
      'Aucune',
      '1 café ou équivalent / jour',
      '2 à 3 cafés / jour',
      'Plus de 3 cafés / jour',
    ],
    memberField: 'caffeine_consumption',
  },
  {
    id: 'q43',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Avez-vous déjà réalisé un bilan nutritionnel ?',
    options: ['Oui, récemment (< 1 an)', 'Oui, il y a plus d\'un an', 'Non, jamais'],
    memberField: 'has_nutrition_assessment',
  },
  {
    id: 'q44',
    category: 'fuel',
    categoryLabel: 'FUEL — Nutrition',
    type: 'single',
    question: 'Votre rapport principal à la nourriture ?',
    options: ['Plaisir avant tout', 'Performance et carburant', 'Santé et longévité', 'Les trois à la fois'],
    memberField: 'food_relationship',
  },

  // ─── ZÉNITH — MENTAL (45-52) ─────────────────────────────────────────────
  {
    id: 'q45',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'scale',
    question: 'Évaluez votre niveau de stress quotidien',
    subtitle: '1 = très serein, 10 = stress permanent',
    min: 1,
    max: 10,
    memberField: 'stress_level',
  },
  {
    id: 'q46',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'multiple',
    question: 'Quelles sont vos principales sources de stress ?',
    options: [
      'Travail et performance',
      'Finances',
      'Relations et famille',
      'Santé',
      'Manque de temps',
      'Compétition / sport',
      'Peu de stress globalement',
    ],
    memberField: 'stress_sources',
  },
  {
    id: 'q47',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'single',
    question: 'Pratiquez-vous la méditation ?',
    options: [
      'Jamais',
      'Parfois (quelques fois par mois)',
      'Régulièrement (1-3x/semaine)',
      'Quotidiennement',
    ],
    memberField: 'meditation_frequency',
  },
  {
    id: 'q48',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'single',
    question: 'Pratiquez-vous des exercices de respiration ?',
    subtitle: 'Cohérence cardiaque, Wim Hof, box breathing…',
    options: ['Oui, régulièrement', 'Parfois', 'Non, jamais'],
    memberField: 'has_breathwork',
  },
  {
    id: 'q49',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'scale',
    question: 'Évaluez votre qualité de concentration au travail',
    subtitle: '1 = très distrait, 10 = focus optimal',
    min: 1,
    max: 10,
    memberField: 'concentration_quality',
  },
  {
    id: 'q50',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'single',
    question: 'Comment décririez-vous votre humeur générale ces derniers mois ?',
    options: [
      'Très positive et stable',
      'Globalement positive',
      'Variable, avec des hauts et des bas',
      'Plutôt difficile en ce moment',
    ],
    memberField: 'mood_general',
  },
  {
    id: 'q51',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'multiple',
    question: 'Quelles pratiques de bien-être mental faites-vous ?',
    options: [
      'Méditation / pleine conscience',
      'Journaling',
      'Thérapie / coaching',
      'Lecture et apprentissage',
      'Nature et déconnexion',
      'Sport comme soupape',
      'Aucune pratique particulière',
    ],
    memberField: 'mental_wellness_practices',
  },
  {
    id: 'q52',
    category: 'zenith',
    categoryLabel: 'ZÉNITH — Mental',
    type: 'single',
    question: 'Avez-vous consulté un professionnel de santé mentale ?',
    options: [
      'Oui, actuellement en suivi',
      'Oui, par le passé',
      'Non, mais j\'y réfléchis',
      'Non, jamais',
    ],
    memberField: 'has_mental_health_professional',
  },

  // ─── ATLAS — EXPÉRIENCES (53-57) ─────────────────────────────────────────
  {
    id: 'q53',
    category: 'atlas',
    categoryLabel: 'ATLAS — Expériences',
    type: 'scale',
    question: 'Votre intérêt pour les expériences physiques extrêmes ou immersives ?',
    subtitle: '1 = pas du tout, 10 = passion absolue',
    min: 1,
    max: 10,
    memberField: 'extreme_experience_interest',
  },
  {
    id: 'q54',
    category: 'atlas',
    categoryLabel: 'ATLAS — Expériences',
    type: 'multiple',
    question: 'Quel type d\'expériences vous attire ?',
    options: [
      'Expéditions montagne / haute altitude',
      'Aventure polaire (Arctique, Antarctique)',
      'Ultramarathon / courses extrêmes',
      'Plongée profonde / apnée',
      'Survie en milieu hostile',
      'Performance mentale extrême',
      'Retraites immersives (silence, jeûne)',
    ],
    memberField: 'experience_types',
  },
  {
    id: 'q55',
    category: 'atlas',
    categoryLabel: 'ATLAS — Expériences',
    type: 'single',
    question: 'Avez-vous déjà participé à une expédition ou un challenge physique majeur ?',
    options: ['Oui, plusieurs fois', 'Oui, une fois', 'Non, c\'est un projet', 'Non, pas pour moi'],
    memberField: 'has_expedition',
  },
  {
    id: 'q56',
    category: 'atlas',
    categoryLabel: 'ATLAS — Expériences',
    type: 'single',
    question: 'Votre niveau de préparation physique pour une expérience ATLAS ?',
    options: [
      'Débutant — il me faudrait 12+ mois de préparation',
      'Intermédiaire — 6-12 mois de préparation',
      'Avancé — 3-6 mois suffiraient',
      'Élite — je peux démarrer dans 3 mois',
    ],
    memberField: 'experience_fitness_level',
  },
  {
    id: 'q57',
    category: 'atlas',
    categoryLabel: 'ATLAS — Expériences',
    type: 'multiple',
    question: 'Quelle durée d\'expérience vous convient ?',
    options: [
      'Week-end (2-3 jours)',
      'Court (1 semaine)',
      'Moyen (2-3 semaines)',
      'Long (1 mois+)',
      'Expédition multi-mois',
    ],
    memberField: 'experience_availability',
  },

  // ─── ORACLE — DONNÉES & WEARABLES (58-65) ────────────────────────────────
  {
    id: 'q58',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Portez-vous un wearable (montre connectée, anneau, capteur) ?',
    options: ['Oui, en permanence', 'Oui, lors de mes entraînements', 'Non'],
    memberField: 'has_wearable',
  },
  {
    id: 'q59',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Quelle marque de wearable utilisez-vous ?',
    subtitle: 'ORACLE synchronisera vos données automatiquement',
    options: [
      'Apple Watch',
      'Garmin',
      'Polar',
      'WHOOP',
      'Oura Ring',
      'Fitbit / Google',
      'Samsung Galaxy',
      'Autre',
      'Aucun',
    ],
    memberField: 'wearable_brand',
  },
  {
    id: 'q60',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Avez-vous déjà réalisé des bilans sanguins complets ?',
    options: ['Oui, régulièrement (< 1 an)', 'Oui, il y a plus d\'un an', 'Non, jamais'],
    memberField: 'has_blood_work',
  },
  {
    id: 'q61',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'scale',
    question: 'Votre intérêt pour les biomarqueurs avancés ?',
    subtitle: '1 = pas du tout, 10 = passion pour la biologie de précision',
    min: 1,
    max: 10,
    memberField: 'biomarker_interest',
  },
  {
    id: 'q62',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Depuis combien de temps suivez-vous votre santé activement ?',
    options: [
      'Moins de 6 mois',
      '6 mois à 1 an',
      '1 à 3 ans',
      'Plus de 3 ans',
    ],
    memberField: 'health_tracking_duration',
  },
  {
    id: 'q63',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Connaissez-vous votre HRV (variabilité de la fréquence cardiaque) ?',
    options: ['Oui, je la suis régulièrement', 'Oui, je connais le concept', 'Non, c\'est quoi ?'],
    memberField: 'knows_hrv',
  },
  {
    id: 'q64',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'multiple',
    question: 'Quelles applications santé ou fitness utilisez-vous ?',
    options: [
      'Strava',
      'MyFitnessPal',
      'Cronometer',
      'Apple Santé / Google Fit',
      'Whoop App',
      'Oura App',
      'Garmin Connect',
      'Aucune en particulier',
    ],
    memberField: 'health_apps',
  },
  {
    id: 'q65',
    category: 'oracle',
    categoryLabel: 'ORACLE — Vos données',
    type: 'single',
    question: 'Comment avez-vous découvert NATICS Lab ?',
    options: [
      'Réseaux sociaux',
      'Bouche à oreille',
      'Presse ou médias',
      'Événement ou podcast',
      'Recommandation d\'un médecin / thérapeute',
      'Autre',
    ],
    memberField: 'referral_source',
  },
]

export const TOTAL_QUESTIONS = QUESTIONS.length // 65
